//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace V1.VS.V2.Vtwo {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ContexteAppel", Namespace="http://schemas.axa.fr/fca/detection/2")]
    [System.SerializableAttribute()]
    public partial class ContexteAppel : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OrigineAppelField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OrigineAppel {
            get {
                return this.OrigineAppelField;
            }
            set {
                if ((object.ReferenceEquals(this.OrigineAppelField, value) != true)) {
                    this.OrigineAppelField = value;
                    this.RaisePropertyChanged("OrigineAppel");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DonneesContratAUTO", Namespace="http://schemas.axa.fr/fca/detection/2")]
    [System.SerializableAttribute()]
    public partial class DonneesContratAUTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DateDeNaissanceConducteurField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DateObtentionPermisField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NumPermisField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PlaqueImmatriculationField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DateDeNaissanceConducteur {
            get {
                return this.DateDeNaissanceConducteurField;
            }
            set {
                if ((this.DateDeNaissanceConducteurField.Equals(value) != true)) {
                    this.DateDeNaissanceConducteurField = value;
                    this.RaisePropertyChanged("DateDeNaissanceConducteur");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DateObtentionPermis {
            get {
                return this.DateObtentionPermisField;
            }
            set {
                if ((this.DateObtentionPermisField.Equals(value) != true)) {
                    this.DateObtentionPermisField = value;
                    this.RaisePropertyChanged("DateObtentionPermis");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NumPermis {
            get {
                return this.NumPermisField;
            }
            set {
                if ((object.ReferenceEquals(this.NumPermisField, value) != true)) {
                    this.NumPermisField = value;
                    this.RaisePropertyChanged("NumPermis");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PlaqueImmatriculation {
            get {
                return this.PlaqueImmatriculationField;
            }
            set {
                if ((object.ReferenceEquals(this.PlaqueImmatriculationField, value) != true)) {
                    this.PlaqueImmatriculationField = value;
                    this.RaisePropertyChanged("PlaqueImmatriculation");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Identifiants", Namespace="http://schemas.axa.fr/fca/detection/2")]
    [System.SerializableAttribute()]
    public partial class Identifiants : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NumClientField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NumAbonneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NumDossierField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NumClient {
            get {
                return this.NumClientField;
            }
            set {
                if ((object.ReferenceEquals(this.NumClientField, value) != true)) {
                    this.NumClientField = value;
                    this.RaisePropertyChanged("NumClient");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public string NumAbonne {
            get {
                return this.NumAbonneField;
            }
            set {
                if ((object.ReferenceEquals(this.NumAbonneField, value) != true)) {
                    this.NumAbonneField = value;
                    this.RaisePropertyChanged("NumAbonne");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public string NumDossier {
            get {
                return this.NumDossierField;
            }
            set {
                if ((object.ReferenceEquals(this.NumDossierField, value) != true)) {
                    this.NumDossierField = value;
                    this.RaisePropertyChanged("NumDossier");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DonneesPersonneAIdentifier", Namespace="http://schemas.axa.fr/fca/detection/2")]
    [System.SerializableAttribute()]
    public partial class DonneesPersonneAIdentifier : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NomField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NomJeuneFilleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PrenomField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VilleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodePostalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TelephoneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DateDeNaissanceField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nom {
            get {
                return this.NomField;
            }
            set {
                if ((object.ReferenceEquals(this.NomField, value) != true)) {
                    this.NomField = value;
                    this.RaisePropertyChanged("Nom");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NomJeuneFille {
            get {
                return this.NomJeuneFilleField;
            }
            set {
                if ((object.ReferenceEquals(this.NomJeuneFilleField, value) != true)) {
                    this.NomJeuneFilleField = value;
                    this.RaisePropertyChanged("NomJeuneFille");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Prenom {
            get {
                return this.PrenomField;
            }
            set {
                if ((object.ReferenceEquals(this.PrenomField, value) != true)) {
                    this.PrenomField = value;
                    this.RaisePropertyChanged("Prenom");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Ville {
            get {
                return this.VilleField;
            }
            set {
                if ((object.ReferenceEquals(this.VilleField, value) != true)) {
                    this.VilleField = value;
                    this.RaisePropertyChanged("Ville");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public string CodePostal {
            get {
                return this.CodePostalField;
            }
            set {
                if ((object.ReferenceEquals(this.CodePostalField, value) != true)) {
                    this.CodePostalField = value;
                    this.RaisePropertyChanged("CodePostal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public string Telephone {
            get {
                return this.TelephoneField;
            }
            set {
                if ((object.ReferenceEquals(this.TelephoneField, value) != true)) {
                    this.TelephoneField = value;
                    this.RaisePropertyChanged("Telephone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=7)]
        public string DateDeNaissance {
            get {
                return this.DateDeNaissanceField;
            }
            set {
                if ((object.ReferenceEquals(this.DateDeNaissanceField, value) != true)) {
                    this.DateDeNaissanceField = value;
                    this.RaisePropertyChanged("DateDeNaissance");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ListeContratDetecte", Namespace="http://schemas.axa.fr/fca/detection/2", ItemName="ContratDetecte")]
    [System.SerializableAttribute()]
    public class ListeContratDetecte : System.Collections.Generic.List<V1.VS.V2.Vtwo.ContratDetecte> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ContratDetecte", Namespace="http://schemas.axa.fr/fca/detection/2")]
    [System.SerializableAttribute()]
    public partial class ContratDetecte : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NumeroContratField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RoleField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NumeroContrat {
            get {
                return this.NumeroContratField;
            }
            set {
                if ((object.ReferenceEquals(this.NumeroContratField, value) != true)) {
                    this.NumeroContratField = value;
                    this.RaisePropertyChanged("NumeroContrat");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Role {
            get {
                return this.RoleField;
            }
            set {
                if ((object.ReferenceEquals(this.RoleField, value) != true)) {
                    this.RoleField = value;
                    this.RaisePropertyChanged("Role");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DetenteurProduit", Namespace="http://schemas.axa.fr/fca/detection/2")]
    [System.SerializableAttribute()]
    public partial class DetenteurProduit : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool DetentionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Detention {
            get {
                return this.DetentionField;
            }
            set {
                if ((this.DetentionField.Equals(value) != true)) {
                    this.DetentionField = value;
                    this.RaisePropertyChanged("Detention");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Distributeur", Namespace="http://schemas.axa.fr/fca/detection/2")]
    [System.SerializableAttribute()]
    public partial class Distributeur : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NumPortefeuilleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ReseauField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NomDistributeurField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VilleDistributeurField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AdresseField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PSNIDTiersField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdPointDeVenteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LibelleCommercialField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NumOriasField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NumPortefeuille {
            get {
                return this.NumPortefeuilleField;
            }
            set {
                if ((object.ReferenceEquals(this.NumPortefeuilleField, value) != true)) {
                    this.NumPortefeuilleField = value;
                    this.RaisePropertyChanged("NumPortefeuille");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Reseau {
            get {
                return this.ReseauField;
            }
            set {
                if ((object.ReferenceEquals(this.ReseauField, value) != true)) {
                    this.ReseauField = value;
                    this.RaisePropertyChanged("Reseau");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public string NomDistributeur {
            get {
                return this.NomDistributeurField;
            }
            set {
                if ((object.ReferenceEquals(this.NomDistributeurField, value) != true)) {
                    this.NomDistributeurField = value;
                    this.RaisePropertyChanged("NomDistributeur");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public string VilleDistributeur {
            get {
                return this.VilleDistributeurField;
            }
            set {
                if ((object.ReferenceEquals(this.VilleDistributeurField, value) != true)) {
                    this.VilleDistributeurField = value;
                    this.RaisePropertyChanged("VilleDistributeur");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public string Adresse {
            get {
                return this.AdresseField;
            }
            set {
                if ((object.ReferenceEquals(this.AdresseField, value) != true)) {
                    this.AdresseField = value;
                    this.RaisePropertyChanged("Adresse");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public string PSNIDTiers {
            get {
                return this.PSNIDTiersField;
            }
            set {
                if ((object.ReferenceEquals(this.PSNIDTiersField, value) != true)) {
                    this.PSNIDTiersField = value;
                    this.RaisePropertyChanged("PSNIDTiers");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public string IdPointDeVente {
            get {
                return this.IdPointDeVenteField;
            }
            set {
                if ((object.ReferenceEquals(this.IdPointDeVenteField, value) != true)) {
                    this.IdPointDeVenteField = value;
                    this.RaisePropertyChanged("IdPointDeVente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=7)]
        public string LibelleCommercial {
            get {
                return this.LibelleCommercialField;
            }
            set {
                if ((object.ReferenceEquals(this.LibelleCommercialField, value) != true)) {
                    this.LibelleCommercialField = value;
                    this.RaisePropertyChanged("LibelleCommercial");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=8)]
        public string NumOrias {
            get {
                return this.NumOriasField;
            }
            set {
                if ((object.ReferenceEquals(this.NumOriasField, value) != true)) {
                    this.NumOriasField = value;
                    this.RaisePropertyChanged("NumOrias");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DonneesPersonneIdentifiee", Namespace="http://schemas.axa.fr/fca/detection/2")]
    [System.SerializableAttribute()]
    public partial class DonneesPersonneIdentifiee : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CiviliteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NomField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NomDeJeuneFilleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PrenomField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NumAbonneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NumFoyerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProfilClientField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RoleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private V1.VS.V2.Vtwo.ListeContact ListeContactField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Adresse1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Adresse2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Adresse3Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Adresse4Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodePostalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VilleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DateDeNaissanceField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Civilite {
            get {
                return this.CiviliteField;
            }
            set {
                if ((object.ReferenceEquals(this.CiviliteField, value) != true)) {
                    this.CiviliteField = value;
                    this.RaisePropertyChanged("Civilite");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nom {
            get {
                return this.NomField;
            }
            set {
                if ((object.ReferenceEquals(this.NomField, value) != true)) {
                    this.NomField = value;
                    this.RaisePropertyChanged("Nom");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NomDeJeuneFille {
            get {
                return this.NomDeJeuneFilleField;
            }
            set {
                if ((object.ReferenceEquals(this.NomDeJeuneFilleField, value) != true)) {
                    this.NomDeJeuneFilleField = value;
                    this.RaisePropertyChanged("NomDeJeuneFille");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Prenom {
            get {
                return this.PrenomField;
            }
            set {
                if ((object.ReferenceEquals(this.PrenomField, value) != true)) {
                    this.PrenomField = value;
                    this.RaisePropertyChanged("Prenom");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public string NumAbonne {
            get {
                return this.NumAbonneField;
            }
            set {
                if ((object.ReferenceEquals(this.NumAbonneField, value) != true)) {
                    this.NumAbonneField = value;
                    this.RaisePropertyChanged("NumAbonne");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public string NumFoyer {
            get {
                return this.NumFoyerField;
            }
            set {
                if ((object.ReferenceEquals(this.NumFoyerField, value) != true)) {
                    this.NumFoyerField = value;
                    this.RaisePropertyChanged("NumFoyer");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public string ProfilClient {
            get {
                return this.ProfilClientField;
            }
            set {
                if ((object.ReferenceEquals(this.ProfilClientField, value) != true)) {
                    this.ProfilClientField = value;
                    this.RaisePropertyChanged("ProfilClient");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=7)]
        public string Role {
            get {
                return this.RoleField;
            }
            set {
                if ((object.ReferenceEquals(this.RoleField, value) != true)) {
                    this.RoleField = value;
                    this.RaisePropertyChanged("Role");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=8)]
        public V1.VS.V2.Vtwo.ListeContact ListeContact {
            get {
                return this.ListeContactField;
            }
            set {
                if ((object.ReferenceEquals(this.ListeContactField, value) != true)) {
                    this.ListeContactField = value;
                    this.RaisePropertyChanged("ListeContact");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=9)]
        public string Adresse1 {
            get {
                return this.Adresse1Field;
            }
            set {
                if ((object.ReferenceEquals(this.Adresse1Field, value) != true)) {
                    this.Adresse1Field = value;
                    this.RaisePropertyChanged("Adresse1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=10)]
        public string Adresse2 {
            get {
                return this.Adresse2Field;
            }
            set {
                if ((object.ReferenceEquals(this.Adresse2Field, value) != true)) {
                    this.Adresse2Field = value;
                    this.RaisePropertyChanged("Adresse2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=11)]
        public string Adresse3 {
            get {
                return this.Adresse3Field;
            }
            set {
                if ((object.ReferenceEquals(this.Adresse3Field, value) != true)) {
                    this.Adresse3Field = value;
                    this.RaisePropertyChanged("Adresse3");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=12)]
        public string Adresse4 {
            get {
                return this.Adresse4Field;
            }
            set {
                if ((object.ReferenceEquals(this.Adresse4Field, value) != true)) {
                    this.Adresse4Field = value;
                    this.RaisePropertyChanged("Adresse4");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=13)]
        public string CodePostal {
            get {
                return this.CodePostalField;
            }
            set {
                if ((object.ReferenceEquals(this.CodePostalField, value) != true)) {
                    this.CodePostalField = value;
                    this.RaisePropertyChanged("CodePostal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=14)]
        public string Ville {
            get {
                return this.VilleField;
            }
            set {
                if ((object.ReferenceEquals(this.VilleField, value) != true)) {
                    this.VilleField = value;
                    this.RaisePropertyChanged("Ville");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=15)]
        public string DateDeNaissance {
            get {
                return this.DateDeNaissanceField;
            }
            set {
                if ((object.ReferenceEquals(this.DateDeNaissanceField, value) != true)) {
                    this.DateDeNaissanceField = value;
                    this.RaisePropertyChanged("DateDeNaissance");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ListeContact", Namespace="http://schemas.axa.fr/fca/detection/2", ItemName="PointDeContact")]
    [System.SerializableAttribute()]
    public class ListeContact : System.Collections.Generic.List<V1.VS.V2.Vtwo.PointDeContact> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PointDeContact", Namespace="http://schemas.axa.fr/fca/detection/2")]
    [System.SerializableAttribute()]
    public partial class PointDeContact : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DetailField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Type {
            get {
                return this.TypeField;
            }
            set {
                if ((object.ReferenceEquals(this.TypeField, value) != true)) {
                    this.TypeField = value;
                    this.RaisePropertyChanged("Type");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public string Detail {
            get {
                return this.DetailField;
            }
            set {
                if ((object.ReferenceEquals(this.DetailField, value) != true)) {
                    this.DetailField = value;
                    this.RaisePropertyChanged("Detail");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Segmentation", Namespace="http://schemas.axa.fr/fca/detection/2")]
    [System.SerializableAttribute()]
    public partial class Segmentation : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SegmentClienteleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool AxaPartenaireField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool VIPField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SegmentClientele {
            get {
                return this.SegmentClienteleField;
            }
            set {
                if ((object.ReferenceEquals(this.SegmentClienteleField, value) != true)) {
                    this.SegmentClienteleField = value;
                    this.RaisePropertyChanged("SegmentClientele");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public bool AxaPartenaire {
            get {
                return this.AxaPartenaireField;
            }
            set {
                if ((this.AxaPartenaireField.Equals(value) != true)) {
                    this.AxaPartenaireField = value;
                    this.RaisePropertyChanged("AxaPartenaire");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public bool VIP {
            get {
                return this.VIPField;
            }
            set {
                if ((this.VIPField.Equals(value) != true)) {
                    this.VIPField = value;
                    this.RaisePropertyChanged("VIP");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="StatutFoyer", Namespace="http://schemas.axa.fr/fca/detection/2")]
    [System.SerializableAttribute()]
    public partial class StatutFoyer : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StatutFCAField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StatutFCA {
            get {
                return this.StatutFCAField;
            }
            set {
                if ((object.ReferenceEquals(this.StatutFCAField, value) != true)) {
                    this.StatutFCAField = value;
                    this.RaisePropertyChanged("StatutFCA");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ServicesIndisponibles", Namespace="http://schemas.axa.fr/fca/detection/2")]
    [System.SerializableAttribute()]
    public partial class ServicesIndisponibles : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ErreurFonctionnelle", Namespace="http://schemas.axa.fr/fca/detection/2")]
    [System.SerializableAttribute()]
    public partial class ErreurFonctionnelle : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="InfoInsuffisantes", Namespace="http://schemas.axa.fr/fca/detection/2")]
    [System.SerializableAttribute()]
    public partial class InfoInsuffisantes : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://services.axa.fr/fca/detection/2", ConfigurationName="Vtwo.IdentifierPersonneContract")]
    public interface IdentifierPersonneContract {
        
        // CODEGEN: Generating message contract since the wrapper name (IdentifierPersonneGenerique) of message IdentifierPersonneGenerique does not match the default value (IdentiferPersonneGenerique)
        [System.ServiceModel.OperationContractAttribute(Action="http://services.axa.fr/fca/detection/2/IdentifierPersonneContract/IdentiferPerson" +
            "neGenerique", ReplyAction="http://services.axa.fr/fca/detection/2/IdentifierPersonneContract/IdentiferPerson" +
            "neGeneriqueResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(V1.VS.V2.Vtwo.ServicesIndisponibles), Action="http://services.axa.fr/fca/detection/2/IdentifierPersonneContract/IdentiferPerson" +
            "neGeneriqueServicesIndisponiblesFault", Name="ServicesIndisponibles", Namespace="http://schemas.axa.fr/fca/detection/2")]
        [System.ServiceModel.FaultContractAttribute(typeof(V1.VS.V2.Vtwo.ErreurFonctionnelle), Action="http://services.axa.fr/fca/detection/2/IdentifierPersonneContract/IdentiferPerson" +
            "neGeneriqueErreurFonctionnelleFault", Name="ErreurFonctionnelle", Namespace="http://schemas.axa.fr/fca/detection/2")]
        [System.ServiceModel.FaultContractAttribute(typeof(V1.VS.V2.Vtwo.InfoInsuffisantes), Action="http://services.axa.fr/fca/detection/2/IdentifierPersonneContract/IdentiferPerson" +
            "neGeneriqueInfoInsuffisantesFault", Name="InfoInsuffisantes", Namespace="http://schemas.axa.fr/fca/detection/2")]
        V1.VS.V2.Vtwo.IdentifierPersonneGeneriqueResponse IdentiferPersonneGenerique(V1.VS.V2.Vtwo.IdentifierPersonneGenerique request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="IdentifierPersonneGenerique", WrapperNamespace="http://services.axa.fr/fca/detection/2", IsWrapped=true)]
    public partial class IdentifierPersonneGenerique {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.axa.fr/fca/detection/2", Order=0)]
        public V1.VS.V2.Vtwo.ContexteAppel ContexteDappel;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.axa.fr/fca/detection/2", Order=1)]
        public V1.VS.V2.Vtwo.DonneesContratAUTO ContratAIdentifier;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.axa.fr/fca/detection/2", Order=2)]
        public V1.VS.V2.Vtwo.Identifiants Identifiants;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.axa.fr/fca/detection/2", Order=3)]
        public V1.VS.V2.Vtwo.DonneesPersonneAIdentifier PersonneAIdentifier;
        
        public IdentifierPersonneGenerique() {
        }
        
        public IdentifierPersonneGenerique(V1.VS.V2.Vtwo.ContexteAppel ContexteDappel, V1.VS.V2.Vtwo.DonneesContratAUTO ContratAIdentifier, V1.VS.V2.Vtwo.Identifiants Identifiants, V1.VS.V2.Vtwo.DonneesPersonneAIdentifier PersonneAIdentifier) {
            this.ContexteDappel = ContexteDappel;
            this.ContratAIdentifier = ContratAIdentifier;
            this.Identifiants = Identifiants;
            this.PersonneAIdentifier = PersonneAIdentifier;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="IdentifierPersonneGeneriqueResponse", WrapperNamespace="http://services.axa.fr/fca/detection/2", IsWrapped=true)]
    public partial class IdentifierPersonneGeneriqueResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.axa.fr/fca/detection/2", Order=0)]
        public short CodeRetour;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.axa.fr/fca/detection/2", Order=1)]
        public V1.VS.V2.Vtwo.ListeContratDetecte ContratsDetectes;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.axa.fr/fca/detection/2", Order=2)]
        public V1.VS.V2.Vtwo.DetenteurProduit DetenteurProduitAppelant;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.axa.fr/fca/detection/2", Order=3)]
        public V1.VS.V2.Vtwo.Distributeur Distrib;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.axa.fr/fca/detection/2", Order=4)]
        public V1.VS.V2.Vtwo.DonneesPersonneIdentifiee PersonneIdentifiee;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.axa.fr/fca/detection/2", Order=5)]
        public V1.VS.V2.Vtwo.Segmentation SegmentationClient;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.axa.fr/fca/detection/2", Order=6)]
        public V1.VS.V2.Vtwo.StatutFoyer StatutDuFoyer;
        
        public IdentifierPersonneGeneriqueResponse() {
        }
        
        public IdentifierPersonneGeneriqueResponse(short CodeRetour, V1.VS.V2.Vtwo.ListeContratDetecte ContratsDetectes, V1.VS.V2.Vtwo.DetenteurProduit DetenteurProduitAppelant, V1.VS.V2.Vtwo.Distributeur Distrib, V1.VS.V2.Vtwo.DonneesPersonneIdentifiee PersonneIdentifiee, V1.VS.V2.Vtwo.Segmentation SegmentationClient, V1.VS.V2.Vtwo.StatutFoyer StatutDuFoyer) {
            this.CodeRetour = CodeRetour;
            this.ContratsDetectes = ContratsDetectes;
            this.DetenteurProduitAppelant = DetenteurProduitAppelant;
            this.Distrib = Distrib;
            this.PersonneIdentifiee = PersonneIdentifiee;
            this.SegmentationClient = SegmentationClient;
            this.StatutDuFoyer = StatutDuFoyer;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IdentifierPersonneContractChannel : V1.VS.V2.Vtwo.IdentifierPersonneContract, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class IdentifierPersonneContractClient : System.ServiceModel.ClientBase<V1.VS.V2.Vtwo.IdentifierPersonneContract>, V1.VS.V2.Vtwo.IdentifierPersonneContract {
        
        public IdentifierPersonneContractClient() {
        }
        
        public IdentifierPersonneContractClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public IdentifierPersonneContractClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IdentifierPersonneContractClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IdentifierPersonneContractClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        V1.VS.V2.Vtwo.IdentifierPersonneGeneriqueResponse V1.VS.V2.Vtwo.IdentifierPersonneContract.IdentiferPersonneGenerique(V1.VS.V2.Vtwo.IdentifierPersonneGenerique request) {
            return base.Channel.IdentiferPersonneGenerique(request);
        }
        
        public short IdentiferPersonneGenerique(V1.VS.V2.Vtwo.ContexteAppel ContexteDappel, V1.VS.V2.Vtwo.DonneesContratAUTO ContratAIdentifier, V1.VS.V2.Vtwo.Identifiants Identifiants, V1.VS.V2.Vtwo.DonneesPersonneAIdentifier PersonneAIdentifier, out V1.VS.V2.Vtwo.ListeContratDetecte ContratsDetectes, out V1.VS.V2.Vtwo.DetenteurProduit DetenteurProduitAppelant, out V1.VS.V2.Vtwo.Distributeur Distrib, out V1.VS.V2.Vtwo.DonneesPersonneIdentifiee PersonneIdentifiee, out V1.VS.V2.Vtwo.Segmentation SegmentationClient, out V1.VS.V2.Vtwo.StatutFoyer StatutDuFoyer) {
            V1.VS.V2.Vtwo.IdentifierPersonneGenerique inValue = new V1.VS.V2.Vtwo.IdentifierPersonneGenerique();
            inValue.ContexteDappel = ContexteDappel;
            inValue.ContratAIdentifier = ContratAIdentifier;
            inValue.Identifiants = Identifiants;
            inValue.PersonneAIdentifier = PersonneAIdentifier;
            V1.VS.V2.Vtwo.IdentifierPersonneGeneriqueResponse retVal = ((V1.VS.V2.Vtwo.IdentifierPersonneContract)(this)).IdentiferPersonneGenerique(inValue);
            ContratsDetectes = retVal.ContratsDetectes;
            DetenteurProduitAppelant = retVal.DetenteurProduitAppelant;
            Distrib = retVal.Distrib;
            PersonneIdentifiee = retVal.PersonneIdentifiee;
            SegmentationClient = retVal.SegmentationClient;
            StatutDuFoyer = retVal.StatutDuFoyer;
            return retVal.CodeRetour;
        }
    }
}
